-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.teacher
(
    "teacherID" integer,
    teacher_name text,
    teacher_surname text,
    password integer,
    gender text,
    dateofbirth date,
    PRIMARY KEY ("teacherID")
);

CREATE TABLE IF NOT EXISTS public.students
(
    "studentID" integer,
    student_name text,
    student_surname text,
    password integer,
    gender text,
    dateofbirth date,
    PRIMARY KEY ("studentID")
);

CREATE TABLE IF NOT EXISTS public.classroom
(
    "classID" integer,
    class_name text,
    capacity integer,
    PRIMARY KEY ("classID")
);

CREATE TABLE IF NOT EXISTS public.lessons
(
    "lessonID" integer,
    "classID" integer,
    "teacherID" integer,
    lesson_name text,
    class_name text,
    PRIMARY KEY ("lessonID")
);

CREATE TABLE IF NOT EXISTS public.lesson_teacher
(
    "lessonID" integer,
    "teacherID" integer,
    PRIMARY KEY ("lessonID")
);

CREATE TABLE IF NOT EXISTS public.lesson_student
(
    "lessonID" integer,
    "studentID" integer,
    midterm integer,
    final integer,
    attendance integer,
    PRIMARY KEY ("lessonID")
);

ALTER TABLE IF EXISTS public.lessons
    ADD FOREIGN KEY ("classID")
    REFERENCES public.classroom ("classID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lessons
    ADD FOREIGN KEY ("teacherID")
    REFERENCES public.teacher ("teacherID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lesson_teacher
    ADD FOREIGN KEY ("lessonID")
    REFERENCES public.lessons ("lessonID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lesson_teacher
    ADD FOREIGN KEY ("teacherID")
    REFERENCES public.teacher ("teacherID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lesson_student
    ADD FOREIGN KEY ("lessonID")
    REFERENCES public.classroom ("classID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lesson_student
    ADD FOREIGN KEY ("studentID")
    REFERENCES public.classroom ("classID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lesson_student
    ADD FOREIGN KEY ("studentID")
    REFERENCES public.students ("studentID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;