# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2  # sec
# from loginstudent import Ui_StudentWindow  # sec


class Ui_StudentWindow_2(object):
    def setupUi(self, StudentWindow):
        StudentWindow.setObjectName("StudentWindow")
        StudentWindow.resize(800, 600)
        StudentWindow.setMinimumSize(QtCore.QSize(800, 600))
        StudentWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(StudentWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 800, 600))
        self.label.setStyleSheet("background-color:rgb(172, 223, 230);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Student_information = QtWidgets.QGroupBox(self.centralwidget)
        self.Student_information.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.Student_information.setMinimumSize(QtCore.QSize(800, 600))
        self.Student_information.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Student_information.setFont(font)
        self.Student_information.setStyleSheet("color:  rgb(143, 106, 185);;")
        self.Student_information.setObjectName("Student_information")
        self.label_2 = QtWidgets.QLabel(self.Student_information)
        self.label_2.setGeometry(QtCore.QRect(140, 40, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Student_information)
        self.label_3.setGeometry(QtCore.QRect(140, 80, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Student_information)
        self.label_4.setGeometry(QtCore.QRect(140, 120, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Student_information)
        self.label_5.setGeometry(QtCore.QRect(140, 160, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Student_information)
        self.label_6.setGeometry(QtCore.QRect(140, 200, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.number_label = QtWidgets.QLabel(self.Student_information)
        self.number_label.setGeometry(QtCore.QRect(340, 40, 225, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.number_label.setFont(font)
        self.number_label.setStyleSheet("background-color: rgb(245, 240, 218);\n"
                                        "color:  rgb(143, 106, 185);")
        self.number_label.setText("")
        self.number_label.setObjectName("number_label")
        self.surname_label = QtWidgets.QLabel(self.Student_information)
        self.surname_label.setGeometry(QtCore.QRect(340, 120, 225, 30))
        self.surname_label.setStyleSheet("background-color: rgb(245, 240, 218);\n"
                                         "color:  rgb(143, 106, 185);")
        self.surname_label.setText("")
        self.surname_label.setObjectName("surname_label")
        self.birth_label = QtWidgets.QLabel(self.Student_information)
        self.birth_label.setGeometry(QtCore.QRect(340, 160, 225, 30))
        self.birth_label.setStyleSheet("background-color: rgb(245, 240, 218);\n"
                                       "color:  rgb(143, 106, 185);")
        self.birth_label.setText("")
        self.birth_label.setObjectName("birth_label")
        self.gender_label = QtWidgets.QLabel(self.Student_information)
        self.gender_label.setGeometry(QtCore.QRect(340, 200, 225, 30))
        self.gender_label.setStyleSheet("background-color: rgb(245, 240, 218);\n"
                                        "color:  rgb(143, 106, 185);")
        self.gender_label.setText("")
        self.gender_label.setObjectName("gender_label")
        self.name_label = QtWidgets.QLabel(self.Student_information)
        self.name_label.setGeometry(QtCore.QRect(340, 80, 225, 30))
        self.name_label.setStyleSheet("background-color: rgb(245, 240, 218);\n"
                                      "color:  rgb(143, 106, 185);")
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.term_widget = QtWidgets.QTableWidget(self.Student_information)
        self.term_widget.setGeometry(QtCore.QRect(50, 270, 661, 238))
        self.term_widget.setStyleSheet("background-color: rgb(245, 240, 218);\n"
                                       "color:  rgb(143, 106, 185);;")
        self.term_widget.setObjectName("term_widget")
        self.term_widget.setColumnCount(3)
        self.term_widget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.term_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.term_widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.term_widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.term_widget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.term_widget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.term_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.term_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.term_widget.setHorizontalHeaderItem(2, item)
        self.term_widget.horizontalHeader().setDefaultSectionSize(197)
        self.term_widget.verticalHeader().setDefaultSectionSize(41)
        self.back_button = QtWidgets.QPushButton(self.Student_information)
        self.back_button.setGeometry(QtCore.QRect(680, 510, 110, 30))
        self.back_button.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(143, 106, 185);\n"
                                       "    color: rgb(245, 240, 218);\n"
                                       "}\n"
                                       "QPushButton::hover{\n"
                                       "    background-color: rgb(115, 80, 139);\n"
                                       "    color: rgb(245, 240, 218);\n"
                                       "}\n"
                                       "QPushButton::pressed{\n"
                                       "    background-color: rgb(81, 65, 108);\n"
                                       "    padding-left:5px;\n"
                                       "    color: rgb(245, 240, 218);\n"
                                       "    padding-top:5px;\n"
                                       "}")
        self.back_button.setObjectName("back_button")
        StudentWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StudentWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        StudentWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StudentWindow)
        self.statusbar.setObjectName("statusbar")
        StudentWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StudentWindow)
        QtCore.QMetaObject.connectSlotsByName(StudentWindow)

    def retranslateUi(self, StudentWindow):
        _translate = QtCore.QCoreApplication.translate
        StudentWindow.setWindowTitle(
            _translate("StudentWindow", "Student Info"))
        self.Student_information.setTitle(
            _translate("StudentWindow", "Student Information"))
        self.label_2.setText(_translate("StudentWindow", "Number:"))
        self.label_3.setText(_translate("StudentWindow", "Name:"))
        self.label_4.setText(_translate("StudentWindow", "Surname:"))
        self.label_5.setText(_translate("StudentWindow", "Date of Birth:"))
        self.label_6.setText(_translate("StudentWindow", "Gender:"))
        item = self.term_widget.verticalHeaderItem(0)
        item.setText(_translate("StudentWindow", "Lesson1"))
        item = self.term_widget.verticalHeaderItem(1)
        item.setText(_translate("StudentWindow", "Lesson2"))
        item = self.term_widget.verticalHeaderItem(2)
        item.setText(_translate("StudentWindow", "Lesson3"))
        item = self.term_widget.verticalHeaderItem(3)
        item.setText(_translate("StudentWindow", "Lesson4"))
        item = self.term_widget.verticalHeaderItem(4)
        item.setText(_translate("StudentWindow", "Lesson5"))
        item = self.term_widget.horizontalHeaderItem(0)
        item.setText(_translate("StudentWindow", "Lesson Name"))
        item = self.term_widget.horizontalHeaderItem(1)
        item.setText(_translate("StudentWindow", "Midterm"))
        item = self.term_widget.horizontalHeaderItem(2)
        item.setText(_translate("StudentWindow", "Final"))
        self.back_button.setText(_translate("StudentWindow", "BACK"))
        self.id = None
  # PostgreSQL verilerini al ve UI elemanlarına yazdır
        self.get_database()

    def get_database(self):

        # # loginstudent.py den gelen idnin buraya yazilmasi
        with open("student_id.txt", "r") as file:
            student_id = file.read()
            print("Studentid su sekilde belirlenmistir: ", student_id)

        # Veritabanı bağlantı bilgileri
        host = "localhost"  # PostgreSQL sunucu adresi
        port = "5432"  # PostgreSQL bağlantı noktası
        database = "schoolmanagement"  # Veritabanı adı
        username = "postgres"  # PostgreSQL kullanıcı adı
        password = "12345"  # PostgreSQL kullanıcı parolası
        try:
            # Yeni veritabanı bağlantısı
            connection = psycopg2.connect(
                host=host,
                port=port,
                database=database,
                user=username,
                password=password
            )

            # Veritabanı işlemleri burada gerçekleştirilir
            cursor = connection.cursor()
            connection.commit()

            # SQL sorgusunu çalıştırma
            cursor.execute(''' SELECT s.student_name, s.student_surname, s.gender, s.dateofbirth, l.lesson_name, ls.midterm, ls.final, l."lessonID"      
                           FROM students s 
                           JOIN lesson_student ls ON s."studentID" = ls."studentID"   
                           JOIN lessons l ON ls."lessonID" = l."lessonID" 
                           WHERE s."studentID" = %s;''', (student_id,))

            # Sonuçları almak
            results = cursor.fetchall()
            for i, row in enumerate(results):
                print("sonuc:", row)

                self.number_label.setText(student_id)
                self.name_label.setText(str(row[0]))
                self.surname_label.setText(str(row[1]))
                self.birth_label.setText(row[2])
                self.gender_label.setText(str(row[3]))

                lesson = row[4]  # Lesson name
                midterm_data = row[5]  # Midterm data
                final_exam_data = row[6]  # Final exam data

                # Set the corresponding items in the table widget
                item_lesson = QtWidgets.QTableWidgetItem(lesson)
                item_midterm = QtWidgets.QTableWidgetItem(str(midterm_data))
                item_final_exam = QtWidgets.QTableWidgetItem(
                    str(final_exam_data))

                # Set the items in the correct columns
                self.term_widget.setItem(i, 0, item_lesson)
                self.term_widget.setItem(i, 1, item_midterm)
                self.term_widget.setItem(i, 2, item_final_exam)

            # Sonuçları işleme
            # for row in results:
            #     # Her bir satırdaki verileri al
            #     studentID, student_name, student_surname, gender, dateofbirth, midterm, final, lessonID, lesson_name = row

            #     # İşlem yapmak veya sonuçları kullanmak için burada kodunuzu yazın
            #     print("-------------------------------------------")
            #     print(
            #         f"Student ID: {studentID}, Name: {student_name}, Surname: {student_surname}, Gender: {gender}, Date of Birth: {dateofbirth}")
            #     print(f"Midterm: {midterm}, Final: {final}")
            #     print(f"Lesson ID: {lessonID}, Lesson Name: {lesson_name}")
            #     print("-------------------------------------------")

            # Bağlantıyı kapatın
            cursor.close()
            connection.close()

            print("Veritabani oluşturuldu ve bağlanti yapildi.")

        except (Exception, psycopg2.Error) as error:
            print("Veritabanina bağlanirken veya oluştururken hata oluştu:", error)


##################
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentWindow = QtWidgets.QMainWindow()
    ui = Ui_StudentWindow_2()
    ui.setupUi(StudentWindow)
    StudentWindow.show()
    sys.exit(app.exec_())
